return {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    lazy = false,
    build = ":TSUpdate",
    config = function()
        require("nvim-treesitter").install {
            "c",
            "cpp",
            "lua",
            "vim",
            "vimdoc",
            "query",
            "go",
            "rust",
            "python",
            "typescript",
            "javascript",
            "html",
            "css",
            "json",
            "yaml",
            "toml",
            "markdown",
            "markdown_inline",
            "bash",
            "nix",
        }
    end,
}
